#!/usr/bin/env ansible-playbook

- hosts: drpservers
  remote_user: drpuser
  roles:
        - role: setup-drp
          tags:
            - firstrun
        - role: drp-server-root
        - role: drp-server
