#!/bin/bash

buildtgt=MYcentos7

case "$1" in
    list)
        drpcli machines list | jq -r '.[] | .Uuid + " " + .Workflow + " " + .Stage'
        ;;
    listd)
        drpcli machines list | jq -r '.[] | .Uuid + " " + .Workflow' |grep discovery
        ;;
    build)
        drpcli machines workflow $2 $buildtgt
        ;;
    delete)
        drpcli machines destroy $2 
        ;;
    buildall)
        for mach in $(drpcli machines list | jq -r '.[] | .Uuid + " " + .Workflow' \
                      | grep discovery$ | awk '{print $1}' ) ; do
            drpcli machines workflow $mach $buildtgt
        done
        ;;
    deleteall)
        for mach in $(drpcli machines list | jq -r '.[].Uuid'); do
            drpcli machines destroy $mach 
        done
        ;;
        



    *)
        echo "Usage: $0 {list|listd|build|buildall|delete|deleteall}"
        exit 1

esac
