#!/bin/bash

buildtgt=MYcentos7


case "$1" in
    listall)
        drpcli machines list | jq -r '.[] | .Uuid + " " + .BootEnv'
        ;;
    listready)
        drpcli machines list | jq -r '.[] | select(.Stage == "sledgehammer-wait") | .Uuid'
        ;;
    buildone)
        drpcli machines workflow $2 $buildtgt
        ;;
    deleteone)
        drpcli machines destroy $2 
        ;;
    buildready)
        for mach in $(drpcli machines list | jq -r '.[] | select(.Stage == "sledgehammer-wait") | .Uuid') ; do
            drpcli machines workflow $mach $buildtgt
        done
        ;;
    deleteall)
        for mach in $(drpcli machines list | jq -r '.[].Uuid'); do
            drpcli machines destroy $mach 
        done
        ;;
        



    *)
        echo "Usage: $0 {list|listready|buildready|deletelall|buildone x|deleteone x}"
        exit 1

esac
