---
- name: add epel
  become: yes
  package:
    name:
        - epel-release

- name: install required packages
  become: yes
  package:
    name:
        - p7zip
        - bsdtar
        - aria2
        - jq
        - golang
        - lbzip2

# My privnet is 10.10.10/24 
# and eth1.  ymmv.  
# The network is also used later for dhcp subnet config.
- name: static network config eth1
  become: yes
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: "^BOOTPROTO="
    line: "BOOTPROTO=none"
    state: present
  notify: restart network

- name: static ip eth1
  become: yes
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    block: |
        IPADDR=10.10.10.3
        PREFIX=24
    marker: "# {mark} ANSIBLE MANAGED"
  notify: restart network

- name: disable firewall
  become: yes
  systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: send our RPM over
  become: yes
  copy:
    src: secrets/dr-provision-3.12.0-9.el7.x86_64.rpm
    dest: /usr/local/etc/drprov.rpm
    mode: 0644
    owner: root
    group: root

- name: install our RPM
  become: yes
  yum:
    name: /usr/local/etc/drprov.rpm
    state: present

- name: install our copy of default content
  become: yes
  copy:
    src: files/drp-community-content.yaml
    dest: /app/PXE/default.yaml
    mode: 0644

- name: start dr-provision
  become: yes
  systemd:
    name: dr-provision
    daemon_reload: yes
    enabled: yes
    state: started

- name: drpuser setup dir
  file:
    path: ~/MYsetup
    state: directory
    mode: 0755

- name: drpuser bin dir
  file:
    path: ~/bin
    state: directory
    mode: 0755

- name: drpcli symlink
  file:
    path: ~/bin/drpcli
    src: /app/PXE/drp-bin/drpcli 
    state: link

- name: ensure drpuser has ssh key
  command: ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ""
  args:
        creates: ~/.ssh/id_rsa.pub

- name: user scripts for by-hand playing
  copy: src=files/{{ item }} dest=~/bin mode=0755
  with_items:
        - dodrp
        - loopit.sh

# Setup has been moved to script with some files.
# All of the below can be done via the API

- name: copy mysetup
  copy:
    src: files/mysetup.sh
    dest: ~/bin/mysetup.sh
    mode: 0755
  notify: run mysetup

- name: copy our setup items
  copy: src=files/{{ item }} dest=~/MYsetup mode=0644
  with_items:
        - nor
        - networks.json
        - sshkey.json
  notify: run mysetup

- meta: end_play

