---
- name: ssh no passwords
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart ssh

- name: ssh no root
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart ssh

# Will need epel to get p7zip.
- name: add epel
  become: yes
  package:
    name:
        - epel-release

- name: install required packages
  become: yes
  package:
    name:
        - p7zip
        - bsdtar
        - aria2
        - jq
        - golang
        - lbzip2

# My privnet is 10.10.10/24 
# and eth1.  ymmv.  
# The network is also used later for dhcp subnet config.
- name: static network config eth1
  become: yes
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: "^BOOTPROTO="
    line: "BOOTPROTO=none"
    state: present
  notify: restart network

- name: static ip eth1
  become: yes
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    block: |
        IPADDR=10.10.10.3
        PREFIX=24
    marker: "# {mark} ANSIBLE MANAGED"
  notify: restart network

- name: disable firewall
  become: yes
  systemd:
    name: firewalld
    enabled: no
    state: stopped


