---
- name: ssh no passwords
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart ssh

- name: ssh no root
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart ssh

# Will need epel to get p7zip.
- name: add epel
  become: yes
  package:
    name:
        - epel-release

- name: install required packages
  become: yes
  package:
    name:
        - p7zip
        - bsdtar
        - aria2
        - jq
